version: '2'
services:
  app:
    build: ./app
    depends_on:
      - api
    ports:
      - "3000:3000"
  api:
    build: ./api
    depends_on:
      - db
    ports:
      - "4000:4000"
  db:
    image: mongo:latest
    ports:
      - "27017:27017"